const http=require('http')
const server=http.createServer((req,res)=>{
    if(req.url==='/')
        res.end('Arun Boi')
    if(req.url==='/about')
        res.end('niggggaa')
   // res.write('welcome')
    res.end(`<h1>404 Error Found</h1>`)
})
server.listen(8000)